### ISSUE TITLE
No matter what I do I get error

### ISSUE THREAD

**Issue by superj707** [pc-coholic/dw-plugin-recaptcha2#1]
The recaptcha wasn't answered correctly.

It's loading under my form but never comes back filled out correctly. Even when it is

**Comment by pc-coholic** [comment]
I am sorry to hear this - but with that little information provided, I cannot help you... From what you're telling me, anything could be not working...

Here is a list of things, that might - or not - be the issue:
- You did not set your own public and private key
- You made a copy-paste-error when entering your public and private key
- Your server cannot contact the API-host to verify the captcha (CURL is beeing used here)
- Your PHP-version isn't even capable of using curl
- You didn't add the correct domain onto the recaptcha-whitelist at Google.

You see, there are many different reasons, why it could be, that this is not working.

Please provide further details, and I'll try to help you to sort it out.

Until then, I'll close this, ok?

FYI: I just tested the plugin on my private wiki and it works fine. So I am fairly certain, we are dealing with some kind of misconfiguration on your server/wiki/recpatcha.
