### ISSUE TITLE
Not working with PHP v7.x.x PHP errors

### ISSUE THREAD

**Issue by raykai** [pc-coholic/dw-plugin-recaptcha2#3]
Hi,
I'm getting some PHP errors when running under PHP v7.x.x im running PHP v 7.1.7 on my server.

Warning: Declaration of action_plugin_recaptcha2::register(&$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in /dokuwiki/lib/plugins/recaptcha2/action.php on line 13

cant get the plugin to work.

**Comment by pc-coholic** [comment]
Could you please let me know, which version of DokuWiki you are running?

To be fair, I haven't used this plugin on PHP7.x yet... So I'll have to investigate this issue myself first.

**Comment by raykai** [comment]
I'm running the latest stable version of DokuWiki: Release 2017-02-19b "Frusterick Manners"

**Comment by pc-coholic** [comment]
I am currently not able to test anything - but perhaps you can :-)

Could you please check if changing in `action.php` from
`function register(&$controller)`

into

`function register(Doku_Event_Handler $controller)`

I saw this change upstream and it could probably fix your problem, too...

**Comment by raykai** [comment]
il try it il let you know tonight

**Comment by raykai** [comment]
ya that seems to fix it .

Tho there is an other prob. il open an other post

**Comment by pc-coholic** [comment]
Thank you very much for your feedback. :-)
