### ISSUE TITLE
 The recaptcha wasn't answered correctly.

### ISSUE THREAD

**Issue by CvH** [pc-coholic/dw-plugin-recaptcha2#5]
If I solve the captcha right I get redirected and the next page tells me ` The recaptcha wasn't answered correctly`. I have no real idea how to debug this, any help is appreciated.

I created another recaptcha v2 "profile" for my wiki at https://www.google.com/recaptcha and entered at the plugin settings my public and private key. Basically it should work.

I am using latest DokuWiki + nginx + php7 + Bootstrap3 Theme.

![image](https://user-images.githubusercontent.com/1355173/30419813-fe409bb6-9937-11e7-847c-41bbc460a0bd.png)

![image](https://user-images.githubusercontent.com/1355173/30419861-25089302-9938-11e7-96a2-6a6622aba9d6.png)

**Btw, the links are broken at the settings.**

![image](https://user-images.githubusercontent.com/1355173/30419638-62449f28-9937-11e7-9c2c-e4dd95aeacc5.png)

**Comment by pc-coholic** [comment]
Hello!

I fixed the links - Thank you for noticing this and letting me know.

As for your problem: sorry, I can't really tell you why this is failing. I haven't been testing the plugin on this particular setup yet

**Comment by CvH** [comment]
tx, is the plugin known working at default skin btw normal setup ?

**Comment by pc-coholic** [comment]
When I initially build this, I ran it on a PHP5/Apache2-server with the default skin - and that worked pretty well...
